package NewPojo;



/**
 * Info generated by hbm2java
 */
public class Info  implements java.io.Serializable {


     private int id;
     private String customerName;
     private String phone;
     private String wallMaterial;
     private Integer numberOfCoating;
     private Integer ceilingArea;
     private Float price;
     private Integer wallArea;

    public Info() {
    }

	
    public Info(int id, String customerName) {
        this.id = id;
        this.customerName = customerName;
    }
    public Info(int id, String customerName, String phone, String wallMaterial, Integer numberOfCoating, Integer ceilingArea, Float price, Integer wallArea) {
       this.id = id;
       this.customerName = customerName;
       this.phone = phone;
       this.wallMaterial = wallMaterial;
       this.numberOfCoating = numberOfCoating;
       this.ceilingArea = ceilingArea;
       this.price = price;
       this.wallArea = wallArea;
    }
   
    public int getId() {
        //return this.id;  
        return 6;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getCustomerName() {
        return this.customerName;
    }
    
    public void setCustomerName(String customerName) {
        this.customerName = customerName;
    }
    public String getPhone() {
        return this.phone;
    }
    
    public void setPhone(String phone) {
        this.phone = phone;
    }
    public String getWallMaterial() {
        return this.wallMaterial;
    }
    
    public void setWallMaterial(String wallMaterial) {
        this.wallMaterial = wallMaterial;
    }
    public Integer getNumberOfCoating() {
        return this.numberOfCoating;
    }
    
    public void setNumberOfCoating(Integer numberOfCoating) {
        this.numberOfCoating = numberOfCoating;
    }
    public Integer getCeilingArea() {
        return this.ceilingArea;
    }
    
    public void setCeilingArea(Integer ceilingArea) {
        this.ceilingArea = ceilingArea;
    }
    public Float getPrice() {
        return this.price;
    }
    
    public void setPrice(Float price) {
        this.price = price;
    }
    public Integer getWallArea() {
        return this.wallArea;
    }
    
    public void setWallArea(Integer wallArea) {
        this.wallArea = wallArea;
    }

}


